package com.zytboa.vo;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_password
     *
     * @mbggenerated
     */
    private String accountPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_image
     *
     * @mbggenerated
     */
    private String accountImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_sex
     *
     * @mbggenerated
     */
    private Integer accountSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_age
     *
     * @mbggenerated
     */
    private Integer accountAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public Account(String accountId, String accountName, String accountPassword, String accountImage, Integer accountSex, Integer accountAge) {
        this.accountId = accountId;
        this.accountName = accountName;
        this.accountPassword = accountPassword;
        this.accountImage = accountImage;
        this.accountSex = accountSex;
        this.accountAge = accountAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public Account() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_id
     *
     * @return the value of account.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_id
     *
     * @param accountId the value for account.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_name
     *
     * @return the value of account.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_name
     *
     * @param accountName the value for account.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_password
     *
     * @return the value of account.account_password
     *
     * @mbggenerated
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_password
     *
     * @param accountPassword the value for account.account_password
     *
     * @mbggenerated
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword == null ? null : accountPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_image
     *
     * @return the value of account.account_image
     *
     * @mbggenerated
     */
    public String getAccountImage() {
        return accountImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_image
     *
     * @param accountImage the value for account.account_image
     *
     * @mbggenerated
     */
    public void setAccountImage(String accountImage) {
        this.accountImage = accountImage == null ? null : accountImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_sex
     *
     * @return the value of account.account_sex
     *
     * @mbggenerated
     */
    public Integer getAccountSex() {
        return accountSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_sex
     *
     * @param accountSex the value for account.account_sex
     *
     * @mbggenerated
     */
    public void setAccountSex(Integer accountSex) {
        this.accountSex = accountSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_age
     *
     * @return the value of account.account_age
     *
     * @mbggenerated
     */
    public Integer getAccountAge() {
        return accountAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_age
     *
     * @param accountAge the value for account.account_age
     *
     * @mbggenerated
     */
    public void setAccountAge(Integer accountAge) {
        this.accountAge = accountAge;
    }
}