package com.zytboa.vo;

public class EmpRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_role.emp_id
     *
     * @mbggenerated
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_role.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    public EmpRoleKey(String empId, String roleId) {
        this.empId = empId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    public EmpRoleKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_role.emp_id
     *
     * @return the value of emp_role.emp_id
     *
     * @mbggenerated
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_role.emp_id
     *
     * @param empId the value for emp_role.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_role.role_id
     *
     * @return the value of emp_role.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_role.role_id
     *
     * @param roleId the value for emp_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}