package com.zytboa.vo;

public class EmpRole extends EmpRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_role.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    public EmpRole(String empId, String roleId, Integer state) {
        super(empId, roleId);
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    public EmpRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_role.state
     *
     * @return the value of emp_role.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_role.state
     *
     * @param state the value for emp_role.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}