package com.zytboa.vo;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_id
     *
     * @mbggenerated
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_type
     *
     * @mbggenerated
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_emp
     *
     * @mbggenerated
     */
    private String logEmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_time
     *
     * @mbggenerated
     */
    private Date logTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    public Log(String logId, String logType, String logEmp, Date logTime) {
        this.logId = logId;
        this.logType = logType;
        this.logEmp = logEmp;
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    public Log() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_id
     *
     * @return the value of log.log_id
     *
     * @mbggenerated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_id
     *
     * @param logId the value for log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_type
     *
     * @return the value of log.log_type
     *
     * @mbggenerated
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_type
     *
     * @param logType the value for log.log_type
     *
     * @mbggenerated
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_emp
     *
     * @return the value of log.log_emp
     *
     * @mbggenerated
     */
    public String getLogEmp() {
        return logEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_emp
     *
     * @param logEmp the value for log.log_emp
     *
     * @mbggenerated
     */
    public void setLogEmp(String logEmp) {
        this.logEmp = logEmp == null ? null : logEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_time
     *
     * @return the value of log.log_time
     *
     * @mbggenerated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_time
     *
     * @param logTime the value for log.log_time
     *
     * @mbggenerated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
}