package com.zytboa.vo;

import java.math.BigDecimal;

public class OrderGoodsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_detail.pre_order_goods_id
     *
     * @mbggenerated
     */
    private String preOrderGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_detail.pre_order_id
     *
     * @mbggenerated
     */
    private String preOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_detail.pre_order_price
     *
     * @mbggenerated
     */
    private Float preOrderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_detail.pre_order_sum
     *
     * @mbggenerated
     */
    private BigDecimal preOrderSum;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    public OrderGoodsDetail(String preOrderGoodsId, String preOrderId, Float preOrderPrice, BigDecimal preOrderSum) {
        this.preOrderGoodsId = preOrderGoodsId;
        this.preOrderId = preOrderId;
        this.preOrderPrice = preOrderPrice;
        this.preOrderSum = preOrderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    public OrderGoodsDetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_detail.pre_order_goods_id
     *
     * @return the value of order_goods_detail.pre_order_goods_id
     *
     * @mbggenerated
     */
    public String getPreOrderGoodsId() {
        return preOrderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_detail.pre_order_goods_id
     *
     * @param preOrderGoodsId the value for order_goods_detail.pre_order_goods_id
     *
     * @mbggenerated
     */
    public void setPreOrderGoodsId(String preOrderGoodsId) {
        this.preOrderGoodsId = preOrderGoodsId == null ? null : preOrderGoodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_detail.pre_order_id
     *
     * @return the value of order_goods_detail.pre_order_id
     *
     * @mbggenerated
     */
    public String getPreOrderId() {
        return preOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_detail.pre_order_id
     *
     * @param preOrderId the value for order_goods_detail.pre_order_id
     *
     * @mbggenerated
     */
    public void setPreOrderId(String preOrderId) {
        this.preOrderId = preOrderId == null ? null : preOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_detail.pre_order_price
     *
     * @return the value of order_goods_detail.pre_order_price
     *
     * @mbggenerated
     */
    public Float getPreOrderPrice() {
        return preOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_detail.pre_order_price
     *
     * @param preOrderPrice the value for order_goods_detail.pre_order_price
     *
     * @mbggenerated
     */
    public void setPreOrderPrice(Float preOrderPrice) {
        this.preOrderPrice = preOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_detail.pre_order_sum
     *
     * @return the value of order_goods_detail.pre_order_sum
     *
     * @mbggenerated
     */
    public BigDecimal getPreOrderSum() {
        return preOrderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_detail.pre_order_sum
     *
     * @param preOrderSum the value for order_goods_detail.pre_order_sum
     *
     * @mbggenerated
     */
    public void setPreOrderSum(BigDecimal preOrderSum) {
        this.preOrderSum = preOrderSum;
    }
}