package com.zytboa.vo;

import java.util.Date;

public class PreOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_order.pre_order_id
     *
     * @mbggenerated
     */
    private String preOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_order.pre_order_amount
     *
     * @mbggenerated
     */
    private Float preOrderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_order.pre_order_date
     *
     * @mbggenerated
     */
    private Date preOrderDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    public PreOrder(String preOrderId, Float preOrderAmount, Date preOrderDate) {
        this.preOrderId = preOrderId;
        this.preOrderAmount = preOrderAmount;
        this.preOrderDate = preOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    public PreOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_order.pre_order_id
     *
     * @return the value of pre_order.pre_order_id
     *
     * @mbggenerated
     */
    public String getPreOrderId() {
        return preOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_order.pre_order_id
     *
     * @param preOrderId the value for pre_order.pre_order_id
     *
     * @mbggenerated
     */
    public void setPreOrderId(String preOrderId) {
        this.preOrderId = preOrderId == null ? null : preOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_order.pre_order_amount
     *
     * @return the value of pre_order.pre_order_amount
     *
     * @mbggenerated
     */
    public Float getPreOrderAmount() {
        return preOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_order.pre_order_amount
     *
     * @param preOrderAmount the value for pre_order.pre_order_amount
     *
     * @mbggenerated
     */
    public void setPreOrderAmount(Float preOrderAmount) {
        this.preOrderAmount = preOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_order.pre_order_date
     *
     * @return the value of pre_order.pre_order_date
     *
     * @mbggenerated
     */
    public Date getPreOrderDate() {
        return preOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_order.pre_order_date
     *
     * @param preOrderDate the value for pre_order.pre_order_date
     *
     * @mbggenerated
     */
    public void setPreOrderDate(Date preOrderDate) {
        this.preOrderDate = preOrderDate;
    }
}