package com.zytboa.vo;

public class Privilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.pri_id
     *
     * @mbggenerated
     */
    private String priId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.pri_name
     *
     * @mbggenerated
     */
    private String priName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbggenerated
     */
    public Privilege(String priId, String priName) {
        this.priId = priId;
        this.priName = priName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbggenerated
     */
    public Privilege() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.pri_id
     *
     * @return the value of privilege.pri_id
     *
     * @mbggenerated
     */
    public String getPriId() {
        return priId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.pri_id
     *
     * @param priId the value for privilege.pri_id
     *
     * @mbggenerated
     */
    public void setPriId(String priId) {
        this.priId = priId == null ? null : priId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.pri_name
     *
     * @return the value of privilege.pri_name
     *
     * @mbggenerated
     */
    public String getPriName() {
        return priName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.pri_name
     *
     * @param priName the value for privilege.pri_name
     *
     * @mbggenerated
     */
    public void setPriName(String priName) {
        this.priName = priName == null ? null : priName.trim();
    }
}