package com.zytboa.vo;

public class SupplierGoodsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.sup_id
     *
     * @mbggenerated
     */
    private String supId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    public SupplierGoodsKey(String supId, String goodsId) {
        this.supId = supId;
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    public SupplierGoodsKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.sup_id
     *
     * @return the value of supplier_goods.sup_id
     *
     * @mbggenerated
     */
    public String getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.sup_id
     *
     * @param supId the value for supplier_goods.sup_id
     *
     * @mbggenerated
     */
    public void setSupId(String supId) {
        this.supId = supId == null ? null : supId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.goods_id
     *
     * @return the value of supplier_goods.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.goods_id
     *
     * @param goodsId the value for supplier_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }
}