package com.zytboa.vo;

import org.springframework.stereotype.Component;

import java.util.UUID;

@Component
public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_id
     *
     * @mbggenerated
     */
    private String supId = UUID.randomUUID().toString().replace("-","");

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_name
     *
     * @mbggenerated
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_linkman
     *
     * @mbggenerated
     */
    private String supLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_phone
     *
     * @mbggenerated
     */
    private String supPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_address
     *
     * @mbggenerated
     */
    private String supAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_remark
     *
     * @mbggenerated
     */
    private String supRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sup_type
     *
     * @mbggenerated
     */
    private String supType;

    private TableMapping tableMapping;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    public Supplier(String supId, String supName, String supLinkman, String supPhone, String supAddress, String supRemark, String supType,TableMapping tableMapping) {
        this.supId = supId;
        this.supName = supName;
        this.supLinkman = supLinkman;
        this.supPhone = supPhone;
        this.supAddress = supAddress;
        this.supRemark = supRemark;
        this.supType = supType;
        this.tableMapping = tableMapping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    public Supplier() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_id
     *
     * @return the value of supplier.sup_id
     *
     * @mbggenerated
     */
    public String getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_id
     *
     * @param supId the value for supplier.sup_id
     *
     * @mbggenerated
     */
    public void setSupId(String supId) {
        this.supId = supId == null ? null : supId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_name
     *
     * @return the value of supplier.sup_name
     *
     * @mbggenerated
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_name
     *
     * @param supName the value for supplier.sup_name
     *
     * @mbggenerated
     */
    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_linkman
     *
     * @return the value of supplier.sup_linkman
     *
     * @mbggenerated
     */
    public String getSupLinkman() {
        return supLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_linkman
     *
     * @param supLinkman the value for supplier.sup_linkman
     *
     * @mbggenerated
     */
    public void setSupLinkman(String supLinkman) {
        this.supLinkman = supLinkman == null ? null : supLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_phone
     *
     * @return the value of supplier.sup_phone
     *
     * @mbggenerated
     */
    public String getSupPhone() {
        return supPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_phone
     *
     * @param supPhone the value for supplier.sup_phone
     *
     * @mbggenerated
     */
    public void setSupPhone(String supPhone) {
        this.supPhone = supPhone == null ? null : supPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_address
     *
     * @return the value of supplier.sup_address
     *
     * @mbggenerated
     */
    public String getSupAddress() {
        return supAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_address
     *
     * @param supAddress the value for supplier.sup_address
     *
     * @mbggenerated
     */
    public void setSupAddress(String supAddress) {
        this.supAddress = supAddress == null ? null : supAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_remark
     *
     * @return the value of supplier.sup_remark
     *
     * @mbggenerated
     */
    public String getSupRemark() {
        return supRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_remark
     *
     * @param supRemark the value for supplier.sup_remark
     *
     * @mbggenerated
     */
    public void setSupRemark(String supRemark) {
        this.supRemark = supRemark == null ? null : supRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sup_type
     *
     * @return the value of supplier.sup_type
     *
     * @mbggenerated
     */
    public String getSupType() {
        return supType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sup_type
     *
     * @param supType the value for supplier.sup_type
     *
     * @mbggenerated
     */
    public void setSupType(String supType) {
        this.supType = supType == null ? null : supType.trim();
    }

    public TableMapping getTableMapping() {
        return tableMapping;
    }

    public void setTableMapping(TableMapping tableMapping) {
        this.tableMapping = tableMapping;
    }
}