package com.zytboa.vo;

import org.springframework.stereotype.Component;

@Component
public class TableMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_mapping.tm_id
     *
     * @mbggenerated
     */
    private Integer tmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_mapping.tm_table_id
     *
     * @mbggenerated
     */
    private String tmTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_mapping.tm_table_col
     *
     * @mbggenerated
     */
    private String tmTableCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_mapping.tm_table_col_key
     *
     * @mbggenerated
     */
    private Integer tmTableColKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_mapping.tm_table_col_val
     *
     * @mbggenerated
     */
    private String tmTableColVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    public TableMapping(Integer tmId, String tmTableId, String tmTableCol, Integer tmTableColKey, String tmTableColVal) {
        this.tmId = tmId;
        this.tmTableId = tmTableId;
        this.tmTableCol = tmTableCol;
        this.tmTableColKey = tmTableColKey;
        this.tmTableColVal = tmTableColVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    public TableMapping() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_mapping.tm_id
     *
     * @return the value of table_mapping.tm_id
     *
     * @mbggenerated
     */
    public Integer getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_mapping.tm_id
     *
     * @param tmId the value for table_mapping.tm_id
     *
     * @mbggenerated
     */
    public void setTmId(Integer tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_mapping.tm_table_id
     *
     * @return the value of table_mapping.tm_table_id
     *
     * @mbggenerated
     */
    public String getTmTableId() {
        return tmTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_mapping.tm_table_id
     *
     * @param tmTableId the value for table_mapping.tm_table_id
     *
     * @mbggenerated
     */
    public void setTmTableId(String tmTableId) {
        this.tmTableId = tmTableId == null ? null : tmTableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_mapping.tm_table_col
     *
     * @return the value of table_mapping.tm_table_col
     *
     * @mbggenerated
     */
    public String getTmTableCol() {
        return tmTableCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_mapping.tm_table_col
     *
     * @param tmTableCol the value for table_mapping.tm_table_col
     *
     * @mbggenerated
     */
    public void setTmTableCol(String tmTableCol) {
        this.tmTableCol = tmTableCol == null ? null : tmTableCol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_mapping.tm_table_col_key
     *
     * @return the value of table_mapping.tm_table_col_key
     *
     * @mbggenerated
     */
    public Integer getTmTableColKey() {
        return tmTableColKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_mapping.tm_table_col_key
     *
     * @param tmTableColKey the value for table_mapping.tm_table_col_key
     *
     * @mbggenerated
     */
    public void setTmTableColKey(Integer tmTableColKey) {
        this.tmTableColKey = tmTableColKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_mapping.tm_table_col_val
     *
     * @return the value of table_mapping.tm_table_col_val
     *
     * @mbggenerated
     */
    public String getTmTableColVal() {
        return tmTableColVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_mapping.tm_table_col_val
     *
     * @param tmTableColVal the value for table_mapping.tm_table_col_val
     *
     * @mbggenerated
     */
    public void setTmTableColVal(String tmTableColVal) {
        this.tmTableColVal = tmTableColVal == null ? null : tmTableColVal.trim();
    }
}