package com.zytboa.dao;

import com.zytboa.vo.EmpRole;
import com.zytboa.vo.EmpRoleKey;

public interface EmpRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EmpRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    int insert(EmpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    int insertSelective(EmpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    EmpRole selectByPrimaryKey(EmpRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmpRole record);
}