package com.zytboa.dao;

import com.zytboa.vo.OrderGoodsDetail;

public interface OrderGoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String preOrderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    int insert(OrderGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    OrderGoodsDetail selectByPrimaryKey(String preOrderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderGoodsDetail record);
}