package com.zytboa.dao;

import com.zytboa.vo.PreOrder;

public interface PreOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String preOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    int insert(PreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    int insertSelective(PreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    PreOrder selectByPrimaryKey(String preOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PreOrder record);
}