package com.zytboa.dao;

import com.zytboa.vo.RolePriKey;

public interface RolePriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_pri
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(RolePriKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_pri
     *
     * @mbggenerated
     */
    int insert(RolePriKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_pri
     *
     * @mbggenerated
     */
    int insertSelective(RolePriKey record);
}