package com.zytboa.dao;

import com.zytboa.vo.SupplierGoodsKey;

public interface SupplierGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SupplierGoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    int insert(SupplierGoodsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    int insertSelective(SupplierGoodsKey record);
}