package com.zytboa.dao;

import com.zytboa.vo.TableMapping;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("tableMappingMapper")
public interface TableMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    int insert(TableMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    int insertSelective(TableMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    TableMapping selectByPrimaryKey(Integer tmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableMapping record);

    List<TableMapping> selectByTableId(TableMapping record);

    List<TableMapping> selectByTableIdAndCol(TableMapping record);

}